export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "contains", value: "iLike" as const, operator: "~~*" },
    { label: "does_not_contain", value: "notILike" as const, operator: "!~~*" },
    { label: "is", value: "eq" as const, operator: "=" },
    { label: "is_not", value: "ne" as const, operator: "!=" },
    { label: "is_empty", value: "isEmpty" as const, operator: "is" },
    { label: "is_not_empty", value: "isNotEmpty" as const, operator: "!is" },
  ],
  numericOperators: [
    { label: "is", value: "eq" as const, operator: "=" },
    { label: "is_not", value: "ne" as const, operator: "!=" },
    { label: "is_less_than", value: "lt" as const, operator: "<" },
    {
      label: "is_less_than_or_equal_to",
      value: "lte" as const,
      operator: "<=",
    },
    { label: "is_greater_than", value: "gt" as const, operator: ">" },
    {
      label: "is_greater_than_or_equal_to",
      value: "gte" as const,
      operator: ">=",
    },
    { label: "is_between", value: "isBetween" as const, operator: "between" },
    { label: "is_empty", value: "isEmpty" as const, operator: "is" },
    { label: "is_not_empty", value: "isNotEmpty" as const, operator: "!is" },
  ],
  dateOperators: [
    { label: "is", value: "eq" as const, operator: "=" },
    { label: "is_not", value: "ne" as const, operator: "!=" },
    { label: "is_before", value: "lt" as const, operator: "<" },
    { label: "is_after", value: "gt" as const, operator: ">" },
    { label: "is_on_or_before", value: "lte" as const, operator: "<=" },
    { label: "is_on_or_after", value: "gte" as const, operator: ">=" },
    { label: "is_between", value: "isBetween" as const, operator: "between" },
    { label: "is_empty", value: "isEmpty" as const, operator: "is" },
    { label: "is_not_empty", value: "isNotEmpty" as const, operator: "!is" },
  ],
  selectOperators: [
    { label: "is", value: "eq" as const, operator: "=" },
    { label: "is_not", value: "ne" as const, operator: "!=" },
    { label: "is_empty", value: "isEmpty" as const, operator: "is" },
    { label: "is_not_empty", value: "isNotEmpty" as const, operator: "!is" },
  ],
  multiSelectOperators: [
    { label: "has_any_of", value: "inArray" as const, operator: "in" },
    { label: "has_none_of", value: "notInArray" as const, operator: "not in" },
    { label: "is_empty", value: "isEmpty" as const, operator: "is" },
    { label: "is_not_empty", value: "isNotEmpty" as const, operator: "!is" },
  ],
  booleanOperators: [
    { label: "is", value: "eq" as const, operator: "=" },
    { label: "is_not", value: "ne" as const, operator: "!=" },
  ],
  uuidOperators: [
    { label: "is", value: "eq" as const, operator: "=" },
    { label: "is_not", value: "ne" as const, operator: "!=" },
  ],
  sortOrders: [
    { label: "Asc", value: "asc" as const, operator: "asc" },
    { label: "Desc", value: "desc" as const, operator: "desc" },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
    "uuid",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
    "uuid",
  ] as const,
  joinOperators: ["and", "or"] as const,
};
