-- Deploy cryptolize:002_role_permissions_table to pg

BEGIN;

create table public.role_permissions (
  id bigint generated by default as identity not null,
  role text not null,
  permission text not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid null default auth.uid (),
  constraint role_permissions_pkey primary key (id),
  constraint role_permissions_role_permission_key unique (role, permission)
) TABLESPACE pg_default;

create index IF not exists idx_role_permissions_role on public.role_permissions using btree (role) TABLESPACE pg_default;

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "select_own_role_permissions" ON "public"."role_permissions" FOR SELECT USING (("role" = (( SELECT "auth"."jwt"() AS "jwt") ->> 'user_role'::"text")));

COMMIT;
