-- Deploy cryptolize:004_init_mpd to pg

BEGIN;

--------------------------------------------------------
-- Create wallet table
--------------------------------------------------------
CREATE TYPE "public"."wallet_type" AS ENUM ('centralized', 'decentralized');

CREATE TABLE public.wallet (
    "id" integer generated by default as identity not null,
    "address" TEXT,
    "blockchain" TEXT NOT NULL DEFAULT 'All',
    "exchange" TEXT,
    "name" TEXT NOT NULL,
    "type" wallet_type NOT NULL,
    "sync_at" timestamp with time zone null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    "profile_id" uuid not null default auth.uid (),
    CONSTRAINT "wallet_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "wallet_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id")
);

create index IF not exists idx_wallet_profile_id on public.wallet using btree (profile_id) TABLESPACE pg_default;

create index IF not exists idx_wallet_address on public.wallet using btree (address) TABLESPACE pg_default;

ALTER TABLE public.wallet ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE TRIGGER "handle_wallet_updated_at" BEFORE UPDATE ON "public"."wallet" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

--------------------------------------------------------
-- Create crypto table
--------------------------------------------------------
CREATE TABLE public.crypto (
    "id" integer generated by default as identity not null,
    "asset" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "digit" INTEGER NOT NULL,
    "logo_url" TEXT NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USDT',
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    CONSTRAINT "crypto_pkey" PRIMARY KEY ("id")
);

ALTER TABLE public.crypto ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE TRIGGER "handle_crypto_updated_at" BEFORE UPDATE ON "public"."crypto" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

--------------------------------------------------------
-- Create wallet_cryptos table
--------------------------------------------------------
CREATE TABLE public.wallet_cryptos (
    "wallet_id" INTEGER NOT NULL,
    "crypto_id" INTEGER NOT NULL,
    CONSTRAINT "wallet_cryptos_pkey" PRIMARY KEY ("wallet_id","crypto_id")
);

ALTER TABLE public.wallet_cryptos ENABLE ROW LEVEL SECURITY;

--------------------------------------------------------
-- Create balance table
--------------------------------------------------------
CREATE TABLE public.balance_history (
    "id" integer generated by default as identity not null,
    "nb_token" DOUBLE PRECISION NOT NULL,
    "price" DOUBLE PRECISION,
    "price24h" DOUBLE PRECISION,
    "date" timestamp with time zone NOT NULL DEFAULT now(),
    "percent" DOUBLE PRECISION,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    "wallet_id" INTEGER NOT NULL,
    "crypto_id" INTEGER NOT NULL,
    CONSTRAINT "balance_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "balance_history_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "public"."wallet"("id"),
    CONSTRAINT "balance_history_crypto_id_fkey" FOREIGN KEY ("crypto_id") REFERENCES "public"."crypto"("id")
);

ALTER TABLE public.balance_history ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_balance_history_wallet_id ON public.balance_history USING btree (wallet_id);
CREATE INDEX IF NOT EXISTS idx_balance_history_crypto_id ON public.balance_history USING btree (crypto_id);

CREATE OR REPLACE TRIGGER "handle_balance_history_updated_at" BEFORE UPDATE ON "public"."balance_history" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

--------------------------------------------------------
-- Create api_key table
--------------------------------------------------------
CREATE TABLE public.api_key (
    "id" integer generated by default as identity not null,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "write" boolean not null,
    "read" boolean not null,
    "expired_at" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    "wallet_id" INTEGER NOT NULL,
    CONSTRAINT "api_key_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "api_key_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "public"."wallet"("id")
);

ALTER TABLE public.api_key ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_api_key_wallet_id ON public.api_key USING btree (wallet_id);

CREATE OR REPLACE TRIGGER "handle_api_key_updated_at" BEFORE UPDATE ON "public"."api_key" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

--------------------------------------------------------
-- Create strategy table
--------------------------------------------------------
CREATE TABLE public.strategy (
    "id" integer generated by default as identity not null,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT 'No description',
    "execution_delay" integer not null default 60, -- in seconds
    "percent_per_trade_up" double precision not null default 1, -- in percentage
    "percent_per_trade_down" double precision not null default 1, -- in percentage
    "multiplier" double precision not null default 1,
    "starting_multiplier" double precision not null default 1,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    CONSTRAINT "strategy_pkey" PRIMARY KEY ("id")
);

ALTER TABLE public.strategy ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE TRIGGER "handle_strategy_updated_at" BEFORE UPDATE ON "public"."strategy" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

--------------------------------------------------------
-- Create strategy_test table
--------------------------------------------------------
CREATE TABLE public.strategy_test (
    "id" integer generated by default as identity not null,
    "year" INTEGER NOT NULL,
    "starting_price" DOUBLE PRECISION NOT NULL,
    "ending_price" DOUBLE PRECISION NOT NULL,
    "average_price" DOUBLE PRECISION NOT NULL,
    "percent" DOUBLE PRECISION NOT NULL,
    "max_trade_open" INTEGER NOT NULL DEFAULT 0,
    "average_trade_open" INTEGER NOT NULL DEFAULT 0,
    "max_invest" DOUBLE PRECISION NOT NULL,
    "nb_token" DOUBLE PRECISION NOT NULL,
    "fees" DOUBLE PRECISION NOT NULL,
    "nb_trade_closed" INTEGER NOT NULL,
    "nb_trade_open" INTEGER NOT NULL,
    "profit" DOUBLE PRECISION NOT NULL,
    "profit_percent" DOUBLE PRECISION NOT NULL,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    "strategy_id" INTEGER NOT NULL,
    "crypto_id" INTEGER NOT NULL,
    CONSTRAINT "strategy_test_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "unique_strategy_test_year_crypto_id" UNIQUE ("year", "crypto_id"),
    CONSTRAINT "strategy_test_strategy_id_fkey" FOREIGN KEY ("strategy_id") REFERENCES "public"."strategy"("id"),
    CONSTRAINT "strategy_test_crypto_id_fkey" FOREIGN KEY ("crypto_id") REFERENCES "public"."crypto"("id")
);

ALTER TABLE public.strategy_test ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_strategy_test_strategy_id ON public.strategy_test USING btree (strategy_id);
CREATE INDEX IF NOT EXISTS idx_strategy_test_crypto_id ON public.strategy_test USING btree (crypto_id);

CREATE OR REPLACE TRIGGER "handle_strategy_test_updated_at" BEFORE UPDATE ON "public"."strategy_test" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

--------------------------------------------------------
-- Create strategy_test_history table
--------------------------------------------------------
CREATE TABLE public.strategy_test_history (
    "strategy_test_id" integer NOT NULL REFERENCES strategy_test(id),
    "date" date NOT NULL,
    "nb_token" DOUBLE PRECISION NOT NULL,
    "max_trade_open" INTEGER NOT NULL DEFAULT 0,
    "average_trade_open" INTEGER NOT NULL DEFAULT 0,
    "average_price" DOUBLE PRECISION NOT NULL,
    "max_invest" DOUBLE PRECISION NOT NULL,
    "nb_trade_closed" INTEGER NOT NULL,
    "nb_trade_open" INTEGER NOT NULL,
    "profit" DOUBLE PRECISION NOT NULL,
    "profit_percent" DOUBLE PRECISION NOT NULL,
    CONSTRAINT "strategy_test_history_pkey" PRIMARY KEY ("strategy_test_id", "date")
);

ALTER TABLE public.strategy_test_history ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_strategy_test_history_strategy_test_id ON public.strategy_test_history USING btree (strategy_test_id);

--------------------------------------------------------
-- Create bot table
--------------------------------------------------------
CREATE TYPE "public"."bot_status" AS ENUM ('running', 'stopped', 'paused', 'error', 'awaiting_start');

CREATE TABLE public.bot (
    "id" integer generated by default as identity not null,
    "name" TEXT NOT NULL,
    "status" bot_status NOT NULL DEFAULT 'awaiting_start',
    "starting_balance" DOUBLE PRECISION NOT NULL,
    "ending_balance" DOUBLE PRECISION NOT NULL,
    "max_trade_open" INTEGER NOT NULL DEFAULT 0,
    "max_invest" DOUBLE PRECISION NOT NULL,
    "api_key_id" INTEGER NOT NULL,
    "crypto_id" INTEGER NOT NULL,
    "strategie_id" INTEGER NOT NULL,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone null,
    CONSTRAINT "bot_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "bot_api_key_id_fkey" FOREIGN KEY ("api_key_id") REFERENCES "public"."api_key"("id"),
    CONSTRAINT "bot_crypto_id_fkey" FOREIGN KEY ("crypto_id") REFERENCES "public"."crypto"("id"),
    CONSTRAINT "bot_strategie_id_fkey" FOREIGN KEY ("strategie_id") REFERENCES "public"."strategy"("id")
);

ALTER TABLE public.bot ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_bot_api_key_id ON public.bot USING btree (api_key_id);
CREATE INDEX IF NOT EXISTS idx_bot_crypto_id ON public.bot USING btree (crypto_id);
CREATE INDEX IF NOT EXISTS idx_bot_strategie_id ON public.bot USING btree (strategie_id);

CREATE OR REPLACE TRIGGER "handle_bot_updated_at" BEFORE UPDATE ON "public"."bot" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

COMMIT;